TWILIO_WHATSAPP_NUMBER = "+14400000000"
TWILIO_ACCOUNT_SID = "your_account_sid"
TWILIO_AUTH_TOKEN = "your_auth_token"

STOP_CHARGING_AT_PERCENTAGE = "85"
WHATSAPP_MESSAGE_FOR_UNPLUG = "🔋 Battery at 85%! Unplug the charger now."
RECEIVER_WHATSAPP_NUMBER = "+919900000000"